-- Add missing columns for routines
ALTER TABLE routines
  ADD COLUMN IF NOT EXISTS subject VARCHAR NOT NULL,
  ADD COLUMN IF NOT EXISTS teacherId UUID,
  ADD COLUMN IF NOT EXISTS teacherName VARCHAR NOT NULL,
  ADD COLUMN IF NOT EXISTS room VARCHAR NOT NULL,
  ADD COLUMN IF NOT EXISTS time VARCHAR NOT NULL,
  ADD COLUMN IF NOT EXISTS day VARCHAR CHECK (day IN ('Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday')) NOT NULL,
  ADD COLUMN IF NOT EXISTS courseId UUID,
  ADD COLUMN IF NOT EXISTS courseName VARCHAR,
  ADD COLUMN IF NOT EXISTS duration VARCHAR DEFAULT '1 hour',
  ADD COLUMN IF NOT EXISTS createdBy UUID NOT NULL,
  ADD COLUMN IF NOT EXISTS isActive BOOLEAN DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS createdAt TIMESTAMP DEFAULT NOW(),
  ADD COLUMN IF NOT EXISTS updatedAt TIMESTAMP DEFAULT NOW();

-- Add missing columns for attendance
ALTER TABLE attendance
  ADD COLUMN IF NOT EXISTS studentId UUID NOT NULL,
  ADD COLUMN IF NOT EXISTS studentName VARCHAR NOT NULL,
  ADD COLUMN IF NOT EXISTS class VARCHAR NOT NULL,
  ADD COLUMN IF NOT EXISTS date DATE DEFAULT NOW() NOT NULL,
  ADD COLUMN IF NOT EXISTS status VARCHAR CHECK (status IN ('Present','Absent','Late')) DEFAULT 'Present' NOT NULL,
  ADD COLUMN IF NOT EXISTS remarks TEXT,
  ADD COLUMN IF NOT EXISTS teacherId UUID,
  ADD COLUMN IF NOT EXISTS markedBy UUID NOT NULL,
  ADD COLUMN IF NOT EXISTS createdAt TIMESTAMP DEFAULT NOW(),
  ADD COLUMN IF NOT EXISTS updatedAt TIMESTAMP DEFAULT NOW();

-- Add missing columns for learning_materials
ALTER TABLE learning_materials
  ADD COLUMN IF NOT EXISTS title VARCHAR NOT NULL,
  ADD COLUMN IF NOT EXISTS type VARCHAR CHECK (type IN ('Video','Document','Link','YouTube')) NOT NULL,
  ADD COLUMN IF NOT EXISTS url TEXT NOT NULL,
  ADD COLUMN IF NOT EXISTS description TEXT,
  ADD COLUMN IF NOT EXISTS subject VARCHAR,
  ADD COLUMN IF NOT EXISTS teacherId UUID,
  ADD COLUMN IF NOT EXISTS courseId UUID,
  ADD COLUMN IF NOT EXISTS createdBy UUID NOT NULL,
  ADD COLUMN IF NOT EXISTS isPublished BOOLEAN DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS createdAt TIMESTAMP DEFAULT NOW(),
  ADD COLUMN IF NOT EXISTS updatedAt TIMESTAMP DEFAULT NOW();
